### PR TITLE
Add meson build configuration

### PR DESCRIPTION
**Pull request by lovell**
Hi, as discussed in #1 this PR adds a meson build script to allow all the major Linux distributions, macOS Homebrew etc. to start to build, package and distribute this library.

The tests have been updated so they write to their "own" file to allow these to be run in parallel.

It adds GitHub Actions CI configuration, including running the tests via valgrind.

https://github.com/lovell/cgif/actions/runs/1067901844

### CODE REVIEW

**Comment by lovell** [comment]
I've added Windows to the CI matrix but it looks like `gifsicle.exe` can't decode some of the images, or at least thinks they are truncated. It doesn't fail the build anyway, so is probably safe to merge for now then I can investigate later.

https://github.com/lovell/cgif/runs/3164480881?check_suite_focus=true

```
gifsicle.exe:build/all_optim.gif:#1: read error: unknown block type 0 at file offset 180
```

**Comment by dloebl** [comment]
> I've added Windows to the CI matrix but it looks like `gifsicle.exe` can't decode some of the images, or at least thinks they are truncated. It doesn't fail the build anyway, so is probably safe to merge for now then I can investigate later.
> 
> https://github.com/lovell/cgif/runs/3164480881?check_suite_focus=true
> 
> ```
> gifsicle.exe:build/all_optim.gif:#1: read error: unknown block type 0 at file offset 180
> ```

Thanks for all this effort!
I've just tested this on my end on this Windows 10 (Visual Studio 2019) and were able to reproduce this as well.
Seems like the GIF is indeed corrupted. I will have a look into this..

**Review by dloebl — APPROVED** [review]
The meson config and GitHub actions look good. I will merge these changes.
However I do have some notes/questions:
1. Right now there is no library version set. I guess that is something to do once cgif is ready to be distributed.
2. I've read in the meson doc that it's possible to configure cross-compilation targets (e.g. for Windows, macOS + different architectures). That might something to add as well.

**Comment by lovell** [comment]
> Right now there is no library version set. I guess that is something to do once cgif is ready to be distributed.

Yes, that's correct, when you're ready it can be added to the `project` directive:

```diff
--- a/meson.build
+++ b/meson.build
@@ -1,6 +1,7 @@
 project(
   'libcgif',
   'c',
+  version : '0.0.1',
   license : 'MIT',
   default_options : ['c_std=c99'],
 )
```

> I've read in the meson doc that it's possible to configure cross-compilation targets

Yes, meson works well for cross-compilation, and it's usually the consumer that provides the `--cross-file` configuration. Here's an example of compiling for ARM64 on x64 - https://github.com/lovell/sharp-libvips/tree/master/linux-arm64v8

I should probably have included some documentation for building via meson as part of this PR - will do a follow up.

**Pull request merged**
